name: 'Production - https://api.tunad.io'

on:
  push:
    branches: 
      - 'master'
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "teste"
        run: |
          echo "OI"
